version: '3.9'

services:
  db:
    image: postgres:17
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"

  web:
    build: .
    env_file:
      - .env
    environment:
      DEBUG: ${DEBUG}
      SECRET_KEY: ${SECRET_KEY}
      DATABASE_URL: ${DATABASE_URL}
      DJANGO_SETTINGS_MODULE: ${DJANGO_SETTINGS_MODULE}
      ALLOWED_HOSTS: ${ALLOWED_HOSTS}
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    stdin_open: true
    tty: true

volumes:
  postgres_data: